try {
    newGreeting();
} catch {
    console.log("No existe esa funci√≥n");
}